version: '3.9'

services:
  db:
    image: postgres:15
    container_name: warehouse_db
    restart: always
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    container_name: warehouse_app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn warehouse_management.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=warehouse_db
      - DB_USER=warehouse_user
      - DB_PASSWORD=warehouse_pass
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: